### PR TITLE
add jlarue26 as mainainer - update to 1.3.2 after pypi tar.gz upload

### PR DESCRIPTION
**Pull request by rxm7706**
1. @jlarue26 to confirm he wants to be a maintainer.  
2. https://pypi.org/project/dbt-dremio/#files is missing the tar.gz for dbt-core 3.2 
3. This will fail right now and sha256 needs to be updated after source / tar.gz for dbt-core 3.2 is pushed to pypi
4. similar to https://files.pythonhosted.org/packages/96/b4/685f7076622d1be95dc4cbadfac0f993954d96a5e0f61b29d961ac090c16/dbt-dremio-1.3.0.tar.gz

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by jlarue26** [comment]
Thanks @rxm7706 !
Can you please also add @ravjotbrar and @argusli as maintainers?

**Comment by rxm7706** [comment]
> Thanks @rxm7706 ! Can you please also add @ravjotbrar and @ArgusLi as maintainers?
@jlarue26 added the maintainers

`https://pypi.org/project/dbt-dremio/#files is missing the tar.gz for dbt-core 3.2`

is the only issue now - once tar.gz is updated, I will update the SHA from the uploaded tar.gz and you should be all good.

**Comment by leeft95** [comment]
Any updates on this release?

**Pull request closed without merging**
